### ISSUE TITLE
Error with prepareMplusData() when requesting dummy codes for an ordered factor

### ISSUE THREAD

**Issue by e-mcbride** [michaelhallquist/MplusAutomation#161]
When running `prepareMplusData()` and specifying columns I want dummy codes for with argument `dummyCode`, if one of the listed columns is an ordered factor, I get the following error:

```
Error in vapply(df, class, FUN.VALUE = NA_character_) : 
  values must be length 1,
 but FUN(X[[8]]) result is length 2
```

This is because the result of internally used function `class()` on an ordered factor is BOTH `"ordered"` and `"factor"`. This error would occur with any object that has more than one output for `class()`. 

Temporary fix for ordered factors til this is resolved is to change these columns from ordered to non-ordered factors using `factor()` with option `ordered = FALSE`.

**Comment by linem7** [comment]
The error is likely due to the scale function or a similar operation that changes the structure of a variable in your dataset to something other than a simple vector, which prepareMplusData expects. The scale function in R, when applied to a column, transforms it into a scaled version, but it also changes its structure to a matrix with attributes, which is why the length of the result for that column becomes 3 (the scaled values, the mean, and the standard deviation used for scaling) instead of 1 (just the class of the variable).

For a scaled variable, you can convert it back to a numeric vector like so:
```
# Assuming `hsb$mathach` was scaled previously
hsb$mathach <- as.numeric(scale(hsb$mathach))
```
