### ISSUE TITLE
Error in readModels, More than one match...: Value

### ISSUE THREAD

**Issue by robgommans** [michaelhallquist/MplusAutomation#18]
Hi,

I get the following error message when trying to read the output. I am trying to run an intercept only model. Could you please help? Anything I can do to fix this? Thank you very much for your help!

Error in extractValue(pattern = thisField$regexPattern, sectionText, filename,  : 
  More than one match found for parameter: Value

The input file is:

  VARIABLE:
    NAMES ARE 
              schid       !schoolid
              classid
              bf          !breakfast
              bfc         !breakfast_meanbyclass
              bfs         !breakfast_meanbyschool
              bfa         !breakfast_meanbyage
              i_bfcs      !int_breakfast_classschool
              i_bfca;      !int_breakfast_classage

```
USEVARIABLES ARE bf;
CLUSTER IS schid classid;
MISSING IS bf (99);
```

  ANALYSIS:
    TYPE IS THREELEVEL;
    ESTIMATOR IS MLF;

  MODEL:
    %WITHIN%
    bf;

```
%BETWEEN classid%
bf;
!bf@0;

%BETWEEN schid%
bf;
!bf@0;
```

  OUTPUT:
    sampstat standardized;

**Comment by michaelhallquist** [comment]
SRMR extraction for TYPE=THREELEVEL is now supported in the development version. This fix will be included in the upcoming v0.7 release of the package.

**Comment by cbratt** [comment]
I believe we have a similar problem in version 0.8.1 (developmental version), now related to more than one average cluster size.

Using a three-level model in an input file called mlmod_1.inp:

    > test <- readModels("mlmod_1.out")
    Reading model:  mlmod_1.out 
    Error extracting SUMMARY OF DATA in output file: mlmod_1.out
    <simpleError in extractValue(pattern = "^\\s*Average cluster size\\s*", section,     filename, type = "dec"): 
    More than one match found for parameter: ^\s*Average cluster size\s*mlmod_1.out>

**Comment by cjvanlissa** [comment]
Could you upload your output file?

**Comment by cbratt** [comment]
I hope this will do, in spite of some editing.

**Comment by cbratt** [comment]
[sample_output.txt](https://github.com/michaelhallquist/MplusAutomation/files/6720052/sample_output.txt)

I hope this will do, in spite of some editing. 
The extension needs to be renamed from .txt to .out

**Comment by jorgesinval** [comment]
Do you have updates regarding `readModels` with three-level models output? Thank you

**Comment by michaelhallquist** [comment]
Hi all,

I have now added additional code to parse information from the "SUMMARY OF DATA" section for THREELEVEL models. This extracts numbers of clusters, cluster sizes, and ICCs for three-level models. I verified this against the output you uploaded @cbratt. Of note, even though you were getting the error above, all other output sections were extracted as expected ($summaries, $parameters, etc.). I mention this because the package is written to read everything it can, and if some section breaks down, the other sections are still attempted (i.e., the parsing is compartmentalized). So, even when you see these messages, I would look at the objects returned because they may very well have the information you need.

Cheers,
Michael

**Comment by jorgesinval** [comment]
@michaelhallquist, thank you so much!!! Just in time to implement a manuscript I'm working on.
