### ISSUE TITLE
The warning element of result list of readModels does not contain the warnings from Mplus

### ISSUE THREAD

**Issue by mronkko** [michaelhallquist/MplusAutomation#3]
Test case https://gist.github.com/mronkko/5478217

**Comment by sophiestallasch** [comment]
Hello, 

I would like to extract the warnings/ errors that appear in the UNIVARIATE SAMPLE STATISTICS section (directly below the UNIVARIATE HIGHER-ORDER MOMENT DESCRIPTIVE STATISTICS) when using DATA: TYPE = INDIVIDUAL in two- and threelevel analyses in Mplus 8 (e.g., THE STANDARD ERRORS OF THE MODEL PARAMETER ESTIMATES MAY NOT BE TRUSTWORTHY FOR SOME PARAMETERS DUE TO... or THE MODEL ESTIMATION HAS REACHED A SADDLE POINT... ). When using imputed data file lists with DATA: TYPE = IMPUTATION, the targeted warnings/ errors appear in the tech9 output which is not availble for TYPE = INDIVIDUAL. 
Unfortunately, with readModels(target = getwd(), what = "warn_err") only the warnings/ errors at the very beginning of the output file can be extracted. 

Is there any possibility or work-around to achieve this? Any suggestion is welcome.

Many thanks in advance!
Sophie
