### ISSUE TITLE
Model parameters not extracted for EFA

### ISSUE THREAD

**Issue by DaniMori** [michaelhallquist/MplusAutomation#36]
When

ANALYSIS:
    TYPE = EFA <MIN> <MAX>;

the element "parameters" in an object returned by readModels(), or extractModelParameters(), returns an empty list.

**Comment by vtmacox** [comment]
I've run into the same problem too.  I thought it had to do with having tested more than 1 factor in the input file, but when when I separate out different runs for each factor, the parameters are not extracted with either readModels() or extractModelParamters()

**Comment by DaniMori** [comment]
I almost completely wrote the code for this.  I may contribute it to the package in the close future, if accepted...

**Comment by michaelhallquist** [comment]
Right, the package does not support extraction of model parameters for EFA at this time (I believe it provides a message to this effect when you try). Because the formatting is quite different from typical Mplus output, we haven't had time to write a new/adapted parser for such files. But we would be eager to have your help on it, Dani and are happy to review your code.

Michael

**Comment by DaniMori** [comment]
Thank you so much.  Right now I'm really busy with something else, but I'll try to review my code soon and submit it.

I must say I'm quite new to Githun, so apologies in the first place if I screw it up with something... I'll try to find my own way through, but any tips will be much appreciated.

**Comment by sda030** [comment]
Hi @DaniMori, any update on this piece? I've so far been using ESEM to retrieve the parameters and it's a bit annoying. Any help needed?

**Comment by DaniMori** [comment]
Hi, this was completely pushed towards background priority as I was finishing my dissertation.  I never even had the chance to review the code as I had expected, I'm afraid.

Would it be possible to contribute it in a new branch to allow someone else to give it a glance?  How should I do it? Would it be ok if I clone the repo, then branch, and submit a merge request, @michaelhallquist?

Thanks

**Comment by cjvanlissa** [comment]
@DaniMori I'd be willing to review your code. Clone and branch, then message me, I'll check it out.

**Comment by michaelhallquist** [comment]
I'm happy to give this a look, too. I hope to have a bit more time for the package in the fall.

**Comment by DaniMori** [comment]
Hi, I have a preliminary, apparently functional version of this functionality.
I could use some feedback / sample output files to try it. Anyone willing to try it or contribute, please have a look at branch `feature/efa_params` my forked version of the repo:
[](https://github.com/DaniMori/MplusAutomation/tree/feature/efa_params)

Like, not the most efficient code ever (plenty of loops everywhere) but I think it could do it as a first approach.

**Comment by sda030** [comment]
Well done @DaniMori! Works perfectly well with multiple factor solutions, and well-organized output. My model has 86 variables with 9, 10, and 11 factors: reading it with readModels took .48 seconds, which is perhaps not fast for a hundred models, but fast enough for my uses. 

My only suggestion for improvement from a user's perspective would be that the naming of the factor solutions and columns should adhere to MplusAutomation conventions, so avoid spaces, capital letters names starting with a number, and - unless I am mistaken - I think some things are spelled out in full. So instead of 
results$parameters$efa$`9 factors`$corrs$std_errors and then a matrix with column names: "Factor 1", "Factor 2", etc. I would rather recommend:
results$parameters$efa$factors_9$correlations$std_errors and then a data frame with column names "factor_1", "factor_2", and so forth, with row.names dropped and made into a proper column. In other words, very small things to improve.
Thanks!

**Comment by DaniMori** [comment]
You've got a point there, thanks so much for the input!

I changed it as you propose, only for the different EFA model sublists I used the prefix `efa_factors_`; I want the distinction between an EFA solution and the factors in that solution to stand as clear as possible. What do you think?

As for the residuals, they are reported in "row style" in the Mplus output, but maybe it makes more sense either to turn them into a `data.frame` (with a first column with the observable variable names, as you suggest for the loadings), or to add them directly as a latter column to the loadings matrix. Any suggestions?

**Comment by DaniMori** [comment]
Well I don't have any more suggestions, reviews, or tests to try, so I think for now I'm gonna make a merge request... at least to free some space in my mind 😄

**Comment by sda030** [comment]
Nice! I can't think of any features missing.

**Comment by michaelhallquist** [comment]
Thanks for your hard work on this, Dani! I skimmed the code this morning and am encouraged that this will work well in general for EFA outputs. I will try to incorporate this into the package in the next two weeks. I sincerely appreciate your contribution, particularly because my time for development has been scarce this year.

Michael

**Comment by michaelhallquist** [comment]
I have now tested the code on a few outputs and have incorporated it into the main branch of the package. Thanks very much for developing this, Dani! I'm hoping to roll out v0.8 of the package to CRAN in the next month, and this will be part of it.

Michael
