### ISSUE TITLE
Expansion of listed variables does not work for repweights

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#37]
When specifying 
VARIABLE = "REPWEIGHTS = X1-X75;"
it is incorrectly translated to Mplus code as
VARIABLE:
NAMES = X1 X7 X5;
REPWEIGHTS = X1 X7 X5;

Not sure if it only relates to repweights or also other settings where multiple variables are possible.

**Comment by JWiley** [comment]
Thanks for the report.
This behavior is due to the default where if you do not specify the `usevariables` argument, `mplusObject()` attempts to guess what variables need to be included.  Currently, it is not that great at guessing.  It works for some relatively simple cases and when variable names in the dataset do not overlap with anything that might naturally occur in Mplus, but in many instances, it fails.

I will see if I can tighten and improve that process.  It is challenging because Mplus does not have a clean way to extract all variables used in a model from its syntax, but I can do better than I've done so far, especially if others are using it.

In the meantime, the best approach is to tell `mplusObject()` all the variables you need with the `usevariables` argument and you can set `autov = FALSE` to turn off automatic guessing of variable names for cases that are too complex for it.

**Comment by michaelhallquist** [comment]
Hi Josh,

I'm not sure if it's useful, but you might look at the expandCmd function I wrote as part of the mplus2lavaan parser: https://github.com/yrosseel/lavaan/blob/master/R/ctr_mplus2lavaan.R. It expands the hyphens to individual variable names, which might help in this case (though Mplus understands hyphens).

Michael

**Comment by JWiley** [comment]
The development version includes changes that should support expanding variable lists like: X1-X75 correctly now.  It works in the few cases I've tested, but would welcome more testing.
As before if the automatic detection of variable names for the USEVARIABLES fails, a workaround is to set autov=FALSE.
