### ISSUE TITLE
Error in EFA readModels()

### ISSUE THREAD

**Issue by kbr3** [michaelhallquist/MplusAutomation#45]
Hi,

I am not an experienced R user, but wanted to use MplusAutomation.  I have been able to successfully run models in Mplus via R, but cannot seem to extract the information from the output.  I am running an EFA, which terminates normally.  But when I run the command: 

readModels()

I get the following error message in R:

Error in EFASections[thisFactor]:length(outfiletext) : NA/NaN argument

I have been unable to find a solution to this.  Please help!

Thanks!

**Comment by michaelhallquist** [comment]
Hi KBR,

Would you be able to upload the .out file for this model here? That would help us figure out what the problem is. At this time, MplusAutomation provides only minimal support for EFA models given their qualitatively different output format.

Best,
Michael

**Comment by kbr3** [comment]
Thanks!  Any help you could give me would be much appreciated.  I'm hoping to use your package for my dissertation. I have uploaded a pdf version of the .out file. Let me know if you need anything else!
Kim

[aim1socialcohefamar07.pdf](https://github.com/michaelhallquist/MplusAutomation/files/828498/aim1socialcohefamar07.pdf)

**Comment by michaelhallquist** [comment]
Hi Kim,

Would you be able to upload the same file as a .txt file? You can just rename it from .out to .txt so that Github tolerates it. The spacing matters (a lot) when parsing Mplus outputs, so I can't easily work from a PDF.

Thanks,
Michael

**Comment by kbr3** [comment]
Here it is!  Thanks again for looking into this.  Let me know if you need anything else.

Kim
[aim1socialcohefamar07_output.txt](https://github.com/michaelhallquist/MplusAutomation/files/860279/aim1socialcohefamar07_output.txt)

**Comment by michaelhallquist** [comment]
This error occurred because the number of EFA sections output was less than requested. This was noted in a warning "Too many factors were requested for EFA." I changed the parser to use the number of observed summary sections, not the number of expected. Summaries for this model are now extracted as expected in the development version, which will become v0.7. Note that MplusAutomation does not support extracting parameters from EFA outputs. This is a longstanding limitation that is unlikely to change in the near future because a lot of new parsing code would be required (the output sections are quite different).

Hopet this helps,
Michael
