### ISSUE TITLE
More than one match found for parameter error using MODEL = CONFIGURAL METRIC SCALAR;

### ISSUE THREAD

**Issue by jaohar** [michaelhallquist/MplusAutomation#49]
Hello,
I receive the following error message when using the ANALYSIS syntax: MODEL = CONFIGURAL METRIC SCALAR;

`Error in extractValue(pattern = thisField$regexPattern, sectionText, filename,  : More than one match found for parameter: ^Number of Free Parameters`

When requesting these three model types, three seperate 'Number of Free Parameters' lines are present in the output. I am using R 3.4, Mplus 8, and the latest development version of MplusAutomation. My full Mplus output file is attached. Please let me know if there is already a workaround for this problem.

[HLQ1HPS_CFA_GENDER.out.txt](https://github.com/michaelhallquist/MplusAutomation/files/1015752/HLQ1HPS_CFA_GENDER.out.txt)

Thank you very much.

-Jonathan

**Comment by jaohar** [comment]
This looks to be related to issue #18 
Error in readModels, More than one match...: Value

**Comment by m-a-rodgers** [comment]
Hello - 
Just curious, will the addition of dealing with TYPE=THREELEVEL in version 7.0 also address the issue of multiple group MI for the three models and the extraction of all fit statistics? Is there an alternate way to do this at the time being, without writing additional R-code? 
Thank you, 
Melissa

**Comment by michaelhallquist** [comment]
The development version now has Initial support for measurement invariance outputs that have multiple model fit and results sections in one file. At the moment, we only support extracting fit information and results from such files. It would require a major refactor of the code (since these outputs violate the typical structure of Mplus outputs) for all sections. But for your output file, the package now extracts basic sections properly.

Melissa: As for the question of TYPE=THREELEVEL, I'd need to see a full output file to understand what's involved. I would suggest opening a separate issue if this fix does not address your problem.

Best,
Michael
