### ISSUE TITLE
Extraction of R-squared

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#59]
After Mplus 8 the R-squared is not being extracted. I can't see any other difference in output for version 7.4 and 8 than the "Rate of missing" column.

**Comment by michaelhallquist** [comment]
Are you using version 0.7 of the package? I had checked the r2 extraction for Mplus v8 outputs that I have access to. If you have the latest version of MplusAutomation and are still having this problem, would you please attach a .out file (has to be attached as .txt) so that I can have a look at the issue you're encountering?

Thanks,
Michael

**Comment by sda030** [comment]
Yes, using 0.7. Colleague has same problem, also using newest package.
[m1_bsssci_eng.txt](https://github.com/michaelhallquist/MplusAutomation/files/1404685/m1_bsssci_eng.txt)

**Comment by michaelhallquist** [comment]
Thanks for sending this file. I took a look and you're correct that the rate of missing column being added was the problem. Because the parser had never encountered this before, it was not able to determine what to do. I've now fixed this in the development version of the package and your file reads properly. You're welcome to install the development version -- instructions here: https://github.com/michaelhallquist/MplusAutomation. We'll be rolling out v0.7-1 to CRAN pretty soon, too.

Michael
