### ISSUE TITLE
last (in)direct not extracted

### ISSUE THREAD

**Issue by StephanSJ** [michaelhallquist/MplusAutomation#62]
Hey,
first of all thank you very much for your great package.

I think I found a bug concerning indirect effects with readModels().

I did a multiple group analysis with indirect effects specifying the indirect effects of 16 variables in 2 groups. However when i extracted the dataframe "...$indirect$overall" the last direct effect in the first group was missing. Also the list in ...$indirect$overall$summary contains only 95 entries instead of 96 (16 variables * 3 different effect types * 2 groups)

Best,
Stephan

**Comment by michaelhallquist** [comment]
Thanks for the info, Stephan. Would you please upload the .out file here so that we can review it and debug the problem you mention? You'll need to save it with the extension .txt for Github to tolerate the upload.

Thanks,
Michael

**Comment by StephanSJ** [comment]
Sure. Here it is.
Best,
Stephan

[lpgvinc_ind.out.txt](https://github.com/michaelhallquist/MplusAutomation/files/1640914/lpgvinc_ind.out.txt)

**Comment by michaelhallquist** [comment]
Thanks, Stephan. This problem occurred because we hadn't yet handled parsing of indirect effects for multiple groups. I updated the development version to fix this problem and your output now parses as expected (you'll also notice the group column is added to the data.frame). I just uploaded this and related changes to CRAN (it will release as v0.7-1 in the next few days), but you can also get the fixes immediately from the Github version of the package.

Best,
Michael
